### ISSUE TITLE
ERROR:  language "pltclu" does not exist

### ISSUE THREAD

**Issue by mr-yaky** [ome/ansible-role-postgresql#10]
Hi,
can you add an option to install postgresql{{ postgresql_version }}-pltcl package and CREATE LANGUAGE to load the language into the database, please ?

**Comment by joshmoore** [comment]
Sorry, @mr-yaky: we currently do not use or have experience with`pltcl` nor do I foresee our doing so. If you or someone else who is using this role would like to open a minimal impact PR, we will be happy to review it.
