### ISSUE TITLE
invalid mode when writing postgres config file  err: chmod: invalid mode: ‘A+user:postgres:rx:allow’

### ISSUE THREAD

**Issue by michal-barczewski** [ome/ansible-role-postgresql#30]
When running the role with default vars i get error like this:

fatal: [hostname]: FAILED! =>
  msg: |-
    Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:postgres:rx:allow’
    Try 'chmod --help' for more information.
    }). For information on working around this, see https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user

i can work around this by setting
postgresql_become_user: root

but i don't understand why this is even done in the first place?
is there a reason to use become_user for those tasks specifically at all?

**Comment by sbesson** [comment]
Hi @michal-barczewski which PSQL version/Operating System ae you running the playbook against? Also which line of the playbook is failing?

**Comment by michal-barczewski** [comment]
postgresql: 14
os: ubuntu 20.04 lts

i have already set it up so i expect same error won't reoccur, but i will try to replicate it on new vm

**Comment by michal-barczewski** [comment]
It seems this is unrelated to the role itself but more the way ansible handles become when connecting as other user than root, not sure if this changed in recent version.
https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user

Solution is to either install 'acl' package (for setfacl)
or set allow_world_readable_tmpfiles: true in ansible.cfg
