### ISSUE TITLE
Debian 12 : `stats_temp_directory` variable does not work

### ISSUE THREAD

**Issue by technics3** [ome/ansible-role-postgresql#38]
Hi, i'm working with @glyg on deploying omero-server with ansible using some of your roles.

I'm currently trying and install postgresql with ome.postgresql on Debian 12 and i noticed that the postgresql cluster can't start automatically because of the following variable on your `postgresql.conf` template seems to not work with Debian 12 : 

```
stats_temp_directory = '/var/run/postgresql/{{ postgresql_version }}-main.pg_stat_tmp'
```

 Note that i'm trying to deploy postgresql 16, the deployment worked flawlessly with postgresql 12.

I can propose a fix if you want, but i wanted to check with you what postgresql version and what OS your role is compatible and tested with.

**Comment by jburel** [comment]
So far we have been testing with version 12, 13, 14 
we need to add support for newer version 15 and 16. If you are able to contribute, that will be great

We are also running version 16 in our CI infrastructure without any problem. This is not installed via ansible role.

**Comment by technics3** [comment]
Just checked and `stats_temp_directory` is deprecated since postgresql 15, i can modify `postgresql-conf-10-ubuntu.j2` to not include that line when `postgresql_version >= 15` if you're ok with it ?

Edit : Apparently you have a pull request that does exactly what i propose already

**Comment by jburel** [comment]
Could you add to the molecule tests support for version 15 and 16 in that case to be sure?

**Comment by jburel** [comment]
@technics3 Forgot about that PR, we have been focusing on upgrading our system with the current state of the role. 
We will review and add
